/** Lista compacta de países comunes con su emoji de bandera. */
export const PAISES: { emoji: string; nombre: string }[] = [
  { emoji: "🇦🇷", nombre: "Argentina" },
  { emoji: "🇺🇾", nombre: "Uruguay" },
  { emoji: "🇨🇱", nombre: "Chile" },
  { emoji: "🇧🇷", nombre: "Brasil" },
  { emoji: "🇵🇾", nombre: "Paraguay" },
  { emoji: "🇧🇴", nombre: "Bolivia" },
  { emoji: "🇵🇪", nombre: "Perú" },
  { emoji: "🇨🇴", nombre: "Colombia" },
  { emoji: "🇻🇪", nombre: "Venezuela" },
  { emoji: "🇪🇨", nombre: "Ecuador" },
  { emoji: "🇲🇽", nombre: "México" },
  { emoji: "🇺🇸", nombre: "Estados Unidos" },
  { emoji: "🇨🇦", nombre: "Canadá" },
  { emoji: "🇪🇸", nombre: "España" },
  { emoji: "🇫🇷", nombre: "Francia" },
  { emoji: "🇮🇹", nombre: "Italia" },
  { emoji: "🇩🇪", nombre: "Alemania" },
  { emoji: "🇬🇧", nombre: "Reino Unido" },
  { emoji: "🇵🇹", nombre: "Portugal" },
  { emoji: "🇳🇱", nombre: "Países Bajos" },
  { emoji: "🇨🇭", nombre: "Suiza" },
  { emoji: "🇦🇹", nombre: "Austria" },
  { emoji: "🇧🇪", nombre: "Bélgica" },
  { emoji: "🇬🇷", nombre: "Grecia" },
  { emoji: "🇮🇪", nombre: "Irlanda" },
  { emoji: "🇸🇪", nombre: "Suecia" },
  { emoji: "🇳🇴", nombre: "Noruega" },
  { emoji: "🇩🇰", nombre: "Dinamarca" },
  { emoji: "🇫🇮", nombre: "Finlandia" },
  { emoji: "🇮🇸", nombre: "Islandia" },
  { emoji: "🇵🇱", nombre: "Polonia" },
  { emoji: "🇨🇿", nombre: "República Checa" },
  { emoji: "🇭🇺", nombre: "Hungría" },
  { emoji: "🇹🇷", nombre: "Turquía" },
  { emoji: "🇮🇱", nombre: "Israel" },
  { emoji: "🇦🇪", nombre: "Emiratos Árabes" },
  { emoji: "🇪🇬", nombre: "Egipto" },
  { emoji: "🇿🇦", nombre: "Sudáfrica" },
  { emoji: "🇲🇦", nombre: "Marruecos" },
  { emoji: "🇮🇳", nombre: "India" },
  { emoji: "🇹🇭", nombre: "Tailandia" },
  { emoji: "🇻🇳", nombre: "Vietnam" },
  { emoji: "🇮🇩", nombre: "Indonesia" },
  { emoji: "🇸🇬", nombre: "Singapur" },
  { emoji: "🇯🇵", nombre: "Japón" },
  { emoji: "🇰🇷", nombre: "Corea del Sur" },
  { emoji: "🇨🇳", nombre: "China" },
  { emoji: "🇦🇺", nombre: "Australia" },
  { emoji: "🇳🇿", nombre: "Nueva Zelanda" },
  { emoji: "🌎", nombre: "Multipaís" },
];
